Agregar código de conducta en inglés
PyBAQ/website pull request #334
Opened 2022-06-13 22:13 UTC by javierdebug

# Pull request

Closes #317 

## Observaciones

Versión en inglés del Código de conducta.

2022-06-14 16:53 UTC, Scot3004 requested changes

2022-06-14 16:53 UTC, Scot3004 commented on content/codigo-de-conducta/contents+en.lr
> +Like the technical community as a whole, the Pythbon Barranquilla team and community is made up of a mixture of professionals and volunteers from all over the world, working on every aspect of the mi
Creo que aca deberia ir  Python Barranquilla en lugar de  Pythbon Barranquilla

2022-06-14 16:53 UTC, Scot3004 commented on content/codigo-de-conducta/contents+en.lr
> +This code of conduct applies to all spaces managed by the Python Barranquilla project. This includes IRC, the mailing lists, the issue tracker, DSF events, and any other forums created by the project
Cual es el significado de DSF events?, no me suena familiar

2022-06-14 17:20 UTC, pyjavo commented on content/codigo-de-conducta/contents+en.lr
> +This code of conduct applies to all spaces managed by the Python Barranquilla project. This includes IRC, the mailing lists, the issue tracker, DSF events, and any other forums created by the project
Django Software Foundation (de ahí nos basamos para el código de conducta)

2022-06-15 17:15 UTC, pyjavo commented
Ahora se ve mejor ¿se resolvieron los issues con el cambio @Scot3004 ?

2022-06-15 23:42 UTC, Scot3004 commented
Creo que sí, pinta bien

2022-06-15 23:44 UTC, Scot3004 approved these changes
Buen trabajo!!

2022-06-16 01:16 UTC, merged