Render title refactor
PyBAQ/website pull request #410
Opened 2023-06-17 22:03 UTC by Scot3004

# Pull request

No hay un issue asociado a esto, dado que no es en si una funcionalidad o un defecto

## Observaciones

Este pequeño refactor, lo que ayuda es a eliminar codigo html duplicado relacionado con ese bloque azul que aparece en casi todas las páginas, para ello se usa la macro render_title la cual recibe el titulo y renderiza el html

2023-06-18 22:16 UTC, pyjavo requested changes
Por lo que pude ver rápidamente, la página de contacto ahora tiene doble H1 y la imagen aparece corrida hacia abajo

2023-06-18 22:17 UTC, pyjavo commented
...y este issue no debería estar relacionado a la página de contacto 😅

2023-06-18 23:51 UTC, Scot3004 commented
Y la página de contacto no se toco aca

2023-06-18 23:52 UTC, Scot3004 commented
Interesante toca hacer pull de master

2023-06-18 23:56 UTC, Scot3004 commented
Ya puedes revisar que en la página de contacto no aparecen 2 h1

2023-06-19 01:17 UTC, pyjavo approved these changes

2023-06-19 01:17 UTC, merged