Proyectos Python Barranquilla
PyBAQ/website pull request #417
Opened 2023-07-20 18:26 UTC by Scot3004

# Pull request

Tercera tarea de #126 

## Observaciones
Listado con los 6 proyectos, ahora mismo está en orden alfabetico y el listado no muestra ningun detalle

![image](https://github.com/PyBAQ/website/assets/1175402/cad78d5f-9470-425f-bba3-e9c93df7b889)

La página web se ve así de momento
![image](https://github.com/PyBAQ/website/assets/1175402/90d04f4f-2190-473d-9383-72cfe606dec7)

2023-07-20 18:52 UTC, Scot3004 commented
Le puse un pequeño excerpt, para que se parezca mas a https://frontend.cafe/cmyk
![image](https://github.com/PyBAQ/website/assets/1175402/7c8d949a-b06f-49ef-b9be-4dc616bad218)

2023-07-21 23:16 UTC, pyjavo requested changes
Elegante.

Solo un detalle. Faltó el de katsu

github_handle: PyBAQ/katsu

2023-07-24 15:13 UTC, pyjavo requested changes
¡Super!
Las imágenes pueden bajarse más de peso. Se pueden bajar usando algún script o herramientas como https://imagecompressor.com/

2023-07-25 00:15 UTC, pyjavo approved these changes

2023-07-25 00:16 UTC, merged