202307 correcciones generalidades ingenieria datos
PyBAQ/website pull request #420
Opened 2023-07-22 15:46 UTC by andresperezcera

# Pull request

## Observaciones

Aplica cambios segun comentarios de Adam Carruthers. Algunos no pudieron agregarse al texto sino que se agregan como notas al pie. Se añaden algunas fuentes adicionales.

2023-07-24 15:28 UTC, pyjavo requested changes

2023-07-24 15:28 UTC, pyjavo commented on content/blog/generalidades-ingenieria-datos/contents.lr
> +El mundo de la ciencia de datos es enorme e imposible de aprender en su totalidad, pero todo empieza por nociones. Espero que este artículo te funcione como una breve referencia a todos los conceptos
Creo que se puede ahorrarse la repetición usando un "o" entre los perfiles
*Si funciona como una vista general y básica de la ingeniería de datos o la ciencia de datos, ha cumplido su cometido.*

2023-07-24 15:28 UTC, pyjavo commented on content/blog/generalidades-ingenieria-datos/contents.lr
> +La estadística no solo es el inicio sino también la columna vertebral de la ciencia de datos. Nos sirve pensar esto porque la estadística exige o requiere un mínimo de los datos que estudia: que los
Agregar listado para facilitar la lectura en la web y que no se vea muy extenso. Ejemplo:

Pero no solo se trata de estadística, la ciencia de datos tambien incorpora habilidades de:

- ciencias de computación
- estadística
- ciencias de información
- matemáticas
- visualización de datos
- visualización de información
- sonificación de datos
- integración de datos
- diseño gráfico
- sistemas complejos
- comunicación
- negocios.

2023-07-24 15:28 UTC, pyjavo commented on content/blog/generalidades-ingenieria-datos/contents.lr
> +Los modelos de datos de aplicaciones por lo general están creadas usando databases relacionales, esto es, tablas con filas y columnas que representan instancias y atributos respectivamente. A fin de
Favor cambiar spanglish "databases relacionales" a *bases de datos relacionales*

2023-07-24 15:28 UTC, pyjavo commented on content/blog/generalidades-ingenieria-datos/contents.lr
> +Los modelos de datos de aplicaciones por lo general están creadas usando databases relacionales, esto es, tablas con filas y columnas que representan instancias y atributos respectivamente. A fin de
En este párrafo se puede cambiar todas las repeticiones de palabra en inglés "database" por *base de datos* o introducir al lector a las siglas BD (base de datos) si lo que se planea es no repetir mucho la palabra

2023-07-25 01:02 UTC, andresperezcera commented on content/blog/generalidades-ingenieria-datos/contents.lr
> +El mundo de la ciencia de datos es enorme e imposible de aprender en su totalidad, pero todo empieza por nociones. Espero que este artículo te funcione como una breve referencia a todos los conceptos
La intención era sacar la frase haciendo referencia a la ciencia de datos. Al parecer en el proceso la dupliqué y no eliminé la erronea.

2023-07-25 01:02 UTC, andresperezcera commented on content/blog/generalidades-ingenieria-datos/contents.lr
> +La estadística no solo es el inicio sino también la columna vertebral de la ciencia de datos. Nos sirve pensar esto porque la estadística exige o requiere un mínimo de los datos que estudia: que los
Hecho.

2023-07-25 01:06 UTC, andresperezcera commented on content/blog/generalidades-ingenieria-datos/contents.lr
> +Los modelos de datos de aplicaciones por lo general están creadas usando databases relacionales, esto es, tablas con filas y columnas que representan instancias y atributos respectivamente. A fin de
Hecho

2023-07-25 02:41 UTC, pyjavo approved these changes

2023-07-25 02:41 UTC, merged