completa-4tareas-#424
PyBAQ/website pull request #425
Opened 2023-07-29 02:45 UTC by andresperezcera

# Pull request  

Closes #424  

## Observaciones  

Este PR se crea para evidenciar el trabajo realizado en este respecto. Aún falta crear la maqueta de cómo se espera funcione la tabla de contenido y pulir detalles. Esta es una base para facilitar esa discusión.

2023-07-29 19:04 UTC, pyjavo commented
Ok. Si es un trabajo en progreso lo convertiré como draft

2023-08-02 03:19 UTC, pyjavo requested changes
Wowwww. ¡¡Está quedando estupendo!!

¿Qué opinas si revertimos solo algunos cambios del commit 7ea310b? 😅 Agrega solo la corrección a scroll a este PR para revisarlo y aceptarlo.

La idea es planear el diseño y dividir el trabajo que haga falta para que los PR no se vuelvan complejos de revisar.

Mil gracias @andresperezcera  🙏

2023-08-02 16:44 UTC, Scot3004 reviewed
Creo que hay que hacer unos pequeños cambios en el css, debido a que se uso etiquetas en vez de clases

2023-08-03 02:19 UTC, pyjavo approved these changes
Excelente

2023-08-03 02:21 UTC, pyjavo commented on scss/_base.scss
> +  scroll-padding-top: 80px; /* height of sticky header */
Por fa Scott, nos confirmas si ya se hizo este cambio para aceptar

2023-08-03 02:21 UTC, pyjavo commented on scss/pages/_blog.scss
> +  nav{
El CSS se trabajará en el issue #427

2023-08-03 03:11 UTC, Scot3004 commented on scss/_base.scss
> +  scroll-padding-top: 80px; /* height of sticky header */
No se ha hecho, pero podemos dejarlo para el siguiente pr, igual se ve bien 😃

2023-08-03 05:13 UTC, andresperezcera commented
Lo probé en el nav y no me funcionó, también en blog-post y tampoco. Las
páginas que mencionanel truco lo hacen siempre a nivel de HTML. Pero quizá
es algo que no entiendo o hice mal, las pruebas las hice mientras trataba
de entender dónde aplicarlo, al final hice copy paste.

On Wed, Aug 2, 2023, 10:11 PM Sergio C. Orozco Torres <
***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In scss/_base.scss
> <https://github.com/PyBAQ/website/pull/425#discussion_r1282595118>:
>
> > @@ -1,3 +1,8 @@
> +html {
> +  scroll-padding-top: 80px; /* height of sticky header */
>
> No se ha hecho, pero podemos dejarlo para el siguiente pr, igual se ve
> bien 😃
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/PyBAQ/website/pull/425#discussion_r1282595118>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACXPIG5YO5T4VVQPOFCZOZ3XTMJGPANCNFSM6AAAAAA24GN2W4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-08-03 20:13 UTC, andresperezcera commented on scss/pages/_blog.scss
> +  nav{
No es generico, es scss, es solo un NAV que este dentro de un DIV de clase blog-post.

2023-08-03 20:14 UTC, andresperezcera commented on scss/pages/_blog.scss
> +  nav{
Este css en particular se revirtió y quedó en otro issue, no hace parte en este momento del PR

2023-08-03 20:14 UTC, andresperezcera commented on scss/_base.scss
> +html {
No me funcionó a nivel del div, quizá hice algo mal. Los posts de internet que lo mencionan siempre lo muestran a nivel de HTML.

2023-08-03 20:54 UTC, Scot3004 commented on scss/_base.scss
> +html {
Basicamente no funciona, muchas gracias por la respuesta

2023-08-03 20:58 UTC, Scot3004 commented
Excelente trabajo, en el argot popular quedo la gaver

2023-08-03 20:59 UTC, andresperezcera commented
> Excelente trabajo, en el argot popular quedo la gaver

Imposible sin su ayuda

2023-08-03 21:00 UTC, pyjavo approved these changes

2023-08-03 21:00 UTC, merged