Devcontainer testing
PyBAQ/website pull request #436
Opened 2023-08-07 20:17 UTC by Scot3004

# Pull request

Closes #435 

## Observaciones

### devcontainer para testing

Para crear el codespace, ir a la pestaña code > click en los 3 puntos > new with options

![image](https://github.com/PyBAQ/website/assets/1175402/7ad59301-8ab4-48f8-bf62-12bc519e4b66)

Seleccionar en devcontainer configuration "Selenium Tests"
![image](https://github.com/PyBAQ/website/assets/1175402/f3ca9dfd-5403-42ef-9f30-9b48362b25af)

Esta creación de codespaces es mas demorada que la que se usa para la aplicación debido a que debe crear un contenedor para la app, otro para selenium standalone y otro para programar
![image](https://github.com/PyBAQ/website/assets/1175402/fa5cb7d7-bd5e-4e36-ab8a-6488048f63ef)

Y cuando digo bastante es aprox 5 a 10 min
![image](https://github.com/PyBAQ/website/assets/1175402/dd501d50-f58b-4d8c-baaf-60487c606cb8)

Una vez creado ejecuta los tests
![image](https://github.com/PyBAQ/website/assets/1175402/5670d83c-18a1-4ad7-a75c-532ec104711c)

### devcontainer por defecto

Ejecuta lektor
![image](https://github.com/PyBAQ/website/assets/1175402/154cb509-d9aa-4de1-bbcc-70f219c59a7c)

y en otra pestaña node sass
![image](https://github.com/PyBAQ/website/assets/1175402/4ff1bbbe-d92f-4eca-a3bc-03cce57a7040)

2023-08-07 20:18 UTC, Scot3004 commented on test-requirements.txt
> +pytest==7.4.0
Tuve un mero chicharron con pytest, asi que le di su buena actualizada a todos los paquetes

2023-08-07 23:41 UTC, pyjavo requested changes
Por favor revisa en que falló el build

2023-08-08 13:28 UTC, Scot3004 commented
fallo en netlify por esto https://github.com/netlify/build-image/blob/focal/included_software.md

2023-08-09 22:39 UTC, pyjavo approved these changes

2023-08-09 22:39 UTC, merged