docs: Traduccion de la seccion de proyectos al inglés
PyBAQ/website pull request #456
Opened 2023-10-07 21:59 UTC by pyjavo

# Pull request

Closes #126 

## Observaciones

Traducción al inglés de los proyectos

2023-10-09 17:14 UTC, jayfz requested changes
Sugiero los siguientes cambios a la traducción. Pienso que se acerca un poco más a la intención del texto en español.

2023-10-09 17:14 UTC, jayfz commented on content/proyectos/pagina-web/contents+en.lr
> +It is also an excellent opportunity generating tool to familiarize yourself with Jinja templates and the general web development environment. This is a good project to learn how to use git, get famil
```suggestion
It is also an excellent opportunity-generating tool to familiarize yourself with Jinja templates and web development in general. This is also a good project to learn how to use git with, and gain familiarity with Github workflows and  markdown. This is a project in which beginner, intermediate and advanced developers interact.
```

2023-10-09 17:14 UTC, jayfz commented on content/proyectos/pagina-web/contents+en.lr
> +general_objective: Have a place where relevant information is shared for the community
```suggestion
general_objective: Have a place where relevant information is shared with the community
```

2023-10-09 17:14 UTC, jayfz commented on content/proyectos/pagina-web/contents+en.lr
> +motivation: Be an example in the python community showing the relevance and presence of python developers in Barranquilla and its surroundings
```suggestion
motivation: Becoming an example in the python community by showing the relevance and presence of python developers in Barranquilla and its surroundings.
```

2023-10-09 17:14 UTC, jayfz commented on content/proyectos/pagina-web/contents+en.lr
> +- Use the page as a learning environment for web technologies around python (lektor)
```suggestion
- Show the monthly events we host in PyBaq
- Share what we have learned through articles for the community every quarter
- Show where we are located
- Show a small portfolio of those of us who collaborate in PyBaq
- Use the page as a learning environment for web technologies around python (lektor)
```

2023-10-09 17:14 UTC, jayfz commented on content/proyectos/pagina-web/contents+en.lr
> +excerpt: The Python Barranquilla website is the place where knowledge is shared with the community through articles, presentations from previous events are shared
```suggestion
excerpt: The Python Barranquilla website is the place where knowledge is shared with the community through articles, and recorded presentations from previous events.
```

2023-10-09 17:14 UTC, jayfz commented on content/proyectos/temii/contents+en.lr
> +Temii is an application in development that began as part of a series of workshops, this group was still Django Barranquilla at that time. Due to the time invested in its development and the purpose
```suggestion
Temii is an application in development that began as part of a series of workshops, this group was still Django Barranquilla at that time. Due to the time invested in its development and the purpose it serves, it is an application for intermediate and senior programmers.
```

2023-10-09 17:14 UTC, jayfz commented on content/proyectos/temii/contents+en.lr
> +- Keep the history of the events that have been taught
```suggestion
- Allow registration of users who want to propose their talks
- Allow registration of new talks, replacing the old Google form. It should allow entering the speaker's information who can have multiple talks
- Integrate with social media APIs to allow publishing and promoting upcoming talks
- Keep a record of the events that have been hosted
```

2023-10-10 00:25 UTC, pyjavo commented
Listo @jayfz ¿apruebas los cambios?

2023-10-10 01:15 UTC, jayfz requested changes
Solo una pequeña corrección adicional. Esta parte  está duplicada (mi culpa)

2023-10-10 01:15 UTC, jayfz commented on content/proyectos/pagina-web/contents+en.lr
> +and it shows where we are located and who makes up the organizing team.
```suggestion

```

2023-10-10 15:23 UTC, pyjavo commented
Corregido @jayfz Gracias.

2023-10-11 15:29 UTC, merged