tdc-estilo-sobrio-scss
PyBAQ/website pull request #475
Opened 2024-02-09 15:30 UTC by andoresuperesu

# Pull request

Closes #427

## Observaciones

Es una propuesta de diseño sobria basada en Realpython. Se modifican archivos scss:
-scss/_variables.scss
-scss/pages/_blog.scss

El primero para agregar los 2 colores necesarios a la paleta: `$medium-gray` y `$lighter-gray`.
El segundo los estilos formalmente que se aplican a la tabla de contenido.

2024-02-09 16:31 UTC, Scot3004 commented
Podriamos cambiar un poco alguno de estos 2 colores
<img width="332" alt="image" src="https://github.com/PyBAQ/website/assets/1175402/17b14748-98d8-475a-9526-0d27bd2eead5">
tiene muy poco contraste

2024-02-09 16:33 UTC, Scot3004 commented on scss/pages/_blog.scss
> +  nav{
dado que esto aplica para la tabla de contenido, creeria que seria mejor usar en lugar de nav `.tdc`

2024-02-09 16:34 UTC, Scot3004 commented on scss/pages/_blog.scss
> +    li, ul, ul li{
Por que se requiere definir el font size de nuevo en cada nivel de lista?

2024-02-09 16:38 UTC, Scot3004 commented
Me gusta lo planteado en este PR, considero pertinente hacer unos pequeños ajustes, principalmente en el tema del contraste del titulo

2024-02-09 16:41 UTC, Scot3004 requested changes
Me gusta lo planteado en este PR, considero pertinente hacer unos pequeños ajustes, principalmente en el tema del contraste del titulo

2024-02-09 18:16 UTC, pyjavo commented
Se ve genial y el responsive funciona muy bien. 
@Scot3004 de casualidad tienes un color en mente para mejorar el contraste del título (el color de fondo me parece que así ya está perfecto).

Me puse a probar con estos colores:
- #384452  (el del texto. Este me gustó el contraste que genera)
- #212529
- #222222

2024-02-09 19:07 UTC, andoresuperesu commented on scss/pages/_blog.scss
> +  nav{
Lo chistoso es que eso es parte del PR anterior. Eso no se implementó en este, pero puedo hacer el cambio en la plantilla y scss a la vez (lo que se pretendía evitar).

2024-02-09 19:12 UTC, andoresuperesu commented on scss/pages/_blog.scss
> +    li, ul, ul li{
Porque de lo contrario termina del mismo tamaño del texto del articulo y reslta demasiado. Si no es lio, dejo el mismo tamaño de texto del texto principal.

2024-02-09 19:13 UTC, andoresuperesu commented
Espero a que haya consenso de colores para aplicarlos. Los actuales son exactamente los mismos de Real Python.

2024-02-09 19:30 UTC, pyjavo commented on scss/pages/_blog.scss
> +    li, ul, ul li{
Tienes razón. La idea es que no resalte demasiado

2024-02-10 00:09 UTC, andoresuperesu commented
@pyjavo @Scot3004 
Opciones de colores:

## A - #999 (Actual)
![image](https://github.com/PyBAQ/website/assets/11465755/7955e986-31f5-4687-ac99-608f81b42ce3)


## B - #384452
![image](https://github.com/PyBAQ/website/assets/11465755/bc70652e-699a-44a8-8769-6f6ddb15318f)

## C - #212529

![image](https://github.com/PyBAQ/website/assets/11465755/6ccbe2f5-97e7-4a86-9675-f53cdb3392fb)


## D - #222222
![image](https://github.com/PyBAQ/website/assets/11465755/882bc667-7331-491d-ace7-60cd42eccbb4)

2024-02-15 15:30 UTC, merged