Script de creación de eventos para migracion
PyBAQ/website pull request #476
Opened 2024-02-13 01:37 UTC by Scot3004

# Pull request

Closes #394 

## Observaciones

Script de migración de eventos toma los contenidos del databag y los combina con la busqueda en flowblock de eventos

2024-02-20 23:09 UTC, pyjavo requested changes

2024-02-20 23:09 UTC, pyjavo commented on scripts/create_events.py
> +
Por favor agrega `if __name__ == '__main__` de esta forma:

```python
if __name__ == '__main__':
    events = extract_meetup_json("databags/meetup.json")
    attachment_index = attachments()
    transformed_events = [transform_event(event) for event in events["past_events"]]
    load_events(transformed_events)
```

2024-03-19 18:12 UTC, Scot3004 commented on scripts/create_events.py
> +
Que debe hacerse 😃  por que sino en un import se va esa transformación 😛

2024-04-13 16:03 UTC, pyjavo approved these changes

2024-04-13 16:03 UTC, pyjavo commented on scripts/create_events.py
> +
Resuelto

2024-04-13 16:03 UTC, merged