Agrega actualizaciones de contenido a "Una guía completa de Django pa…
PyBAQ/website pull request #478
Opened 2024-02-16 21:34 UTC by CamilaPua

Agrega actualizaciones de contenido a "Una guía completa de Django para principiantes- Parte 1" con didactica de viaje en el tiempo

# Pull request

Closes [#469](https://github.com/PyBAQ/website/issues/469)

## Observaciones

![image](https://github.com/PyBAQ/website/assets/121822505/c3972b82-be81-42db-a01d-df9d93f3e370)

2024-02-17 23:06 UTC, Scot3004 requested changes
Mi impresion general es que me gustan las observaciones, sin embargo, al colocarlas como titulos, desentona con el articulo original, lo que veo es que son como comentarios lo que se muestra en los "viajes temporales", sin embargo me preocupa un poco que se habla como si fuese futuro, cuando en un tiempo dichas versiones ya no van a ser validas, entonces me deja la duda si se esta manejando el tiempo correcto

2024-02-19 00:42 UTC, andoresuperesu commented on content/blog/una-guia-completa-de-django-para-principiantes-parte-1/contents.lr
> +#### Máquina del tiempo.
Quizá este sería el caso perfecto para incluir admonitions (https://www.getlektor.com/plugins/lektor-markdown-admonition/). Pero podría mientras tanto funcionar como menciona @Scot3004 porque de lo contrario no se diferencia del flujo normal del articulo.

2024-02-22 01:22 UTC, pyjavo requested changes
De acuerdo con lo que dice el compañero `Scot3004`

@CamilaPua por fa agrega al final del archivo **contents.lr** la opción para mostrar la tabla de contenidos. De esta forma:

```
---
pub_date: 2017-12-15
---
render_tdc: yes
```

2024-03-14 17:19 UTC, pyjavo commented
@CamilaPua ¿cómo vas?¿necesitas ayuda con algo?

2024-04-28 20:07 UTC, CamilaPua commented on content/blog/una-guia-completa-de-django-para-principiantes-parte-1/contents.lr
> +#### Máquina del tiempo.
> En markdown este tipo de bloques se puede hacer con > por ejemplo:
> 
> > ⚠️ Hola! Este tutorial es del 2017 y  y desde entonces han surgido algunos cambios en Python y Django. Desde la versión 3.3 Python trae en su core _venv_ para crear entornos virtuales así que no es necesario instalar virtualenv, paquete que hoy en día se considera legacy.
> 
> Se escribe asi:
> 
> ```
> > ⚠️ Hola! Este tutorial es del 2017 y  y desde entonces han surgido algunos cambios en Python y Django. Desde la versión 3.3 Python trae en su core *venv* para crear entornos virtuales así que no es necesario instalar virtualenv, paquete que hoy en día se considera legacy.
> ```

![image](https://github.com/PyBAQ/website/assets/121822505/ed6161ee-7649-4ebe-b787-bb054d577926)
así se ve cuando lo pongo
a lo mejor usamos lo que dice Andrés, debo hacer otro PR para eso?

2024-05-02 22:48 UTC, pyjavo commented on content/blog/una-guia-completa-de-django-para-principiantes-parte-1/contents.lr
> +#### Máquina del tiempo.
@CamilaPua Cuando dices "así se ve cuando lo pongo" ¿te refieres a que el tamaño de letra es muy grande, pequeño u otra cosa? **Sugiero que hagas el commit con ese cambio** para nosotros poderlo ver mejor.

@andoresuperesu tener la característica de "admonition tags" suena interesante. Lo que veo en el repositorio https://github.com/lektor/lektor-markdown-admonition/commits/master/ es que parece abandonado. El último commit fue hace 6 años por lo que veo 2 posibles opciones :thinking::

1. Concuerdo en usar la opción que sugiere `Scott3004` sobre los bloques con > para resolver el tema del contenido actualizado (que es la prioridad de este PR) .
2. Luego, podríamos ver si implementamos nosotros una característica similar a "admonitions atgs", pensando en mejorar la experiencia de usuario.

¿Qué opinan?

2024-05-23 17:09 UTC, pyjavo commented
@CamilaPua @andoresuperesu ¿pueden por favor enviar imágenes de ejemplo (o enlaces de proyectos) que usen [admonition/](https://www.getlektor.com/plugins/lektor-markdown-admonition/)?

Para el issue #469 solo se pide actualizar contenido, por lo que sería bueno que en este PR solo se añadan cambios de contenido @CamilaPua Ya luego vemos si necesitamos añadir admonition.

2024-05-29 17:27 UTC, pyjavo commented
@CamilaPua actualicemos solo el contenido por fa. Luego en otro PR veremos como lo organizamos mejor visualmente. 
Por fa ten en cuenta el feedback anterior

2024-07-04 21:10 UTC, pyjavo commented
@CamilaPua actualicé el artículo con la tabla de contenidos para que te sea más fácil verla

https://pybaq.co/blog/una-guia-completa-de-django-para-principiantes-parte-1/

¿Necesitas ayuda con algo?

2024-07-27 16:58 UTC, Scot3004 commented
En respuesta al tema de los blockquotes ya cree el respectivo issue #536  y fix #535 una vez se cierren estos se pueden hacer uso de las citas tal como describe este tutorial https://www.markdowntutorial.com/es/lesson/5/

2024-09-20 16:51 UTC, merged