Content eventos script ejecutado
PyBAQ/website pull request #490
Opened 2024-04-20 00:15 UTC by Scot3004

# Pull request

## Observaciones
Creación de las páginas individuales de eventos

2024-04-20 14:24 UTC, pyjavo requested changes
¡Super! 

1. Por favor actualiza tu rama. No aparecen las diapositivas/fotos/repos ni videos de los eventos a partir de la charla de FIFA 24.
2. En el caso de que quiera limpiar las descripciones de ciertos eventos (por ejemplo, borrar el formulario de ingreso a Koombea), eso tocaria hacerlo manualmente, ¿cierto?

2024-04-20 17:13 UTC, Scot3004 commented
1) buen ojo, no me había dado cuenta, lo hare
2) si, toca hacerlo evento por evento para mejorar esas descripciones, no veo tan viable hacer un script considerando que los eventos en varios casos tienen formatos diferentes

2024-04-20 17:17 UTC, pyjavo commented on templates/nosotros-miembro.html
> +    {% set eventos = site.query('/eventos', alt) | speakerevents(this._id) %}
Este cambio ya se fusionó con la rama principal gracias al otro Pull Request

2024-04-21 17:18 UTC, Scot3004 commented
Paso a paso de la migración

```bash
mv content/eventos content/eventos1
git checkout content-eventos-bak -- content/eventos/contents.lr
python scripts/create_events.py
```

2024-04-21 17:24 UTC, Scot3004 commented on templates/nosotros-miembro.html
> +    {% set eventos = site.query('/eventos', alt) | speakerevents(this._id) %}
Si, lo agregue por que necesitaba ver este cambio, sino no se generaba nada

2024-04-21 17:37 UTC, Scot3004 commented
Para mejor entendimiento separe lo hecho en 3 commits
1: crear una rama con mis cambios de content-eventos, de los cuales los mas importantes son la creación de una nueva pagina de inicio para eventos con el modelo eventos y la edición de algún evento para usarlo de muestra, en este caso el del meetup de septiembre de 2023

# Commit 1

## 1 Hacer backup de la rama content eventos

```bash
git checkout content-eventos
git checkout -b content-eventos-bak
```

## 2 Ir a master y eliminar la rama para sobre escribir los cambios

```bash
git checkout master
git branch -D content-eventos
git checkout -b content-eventos
```

## 3 Crear nuevo indice de eventos, viejo indice movido a `eventos1`

```bash
mv content/eventos content/eventos1
git checkout content-eventos-bak -- content/eventos/contents.lr
```

# Commit 2

ejecutar script para crear los eventos

```bash
python scripts/create_events.py
```

# Commit 3

Restaurar evento de muestra de la rama original content-eventos

git checkout content-eventos-bak -- content/eventos/2023-09-21-serverless-devcontainers-en-localhost-automatizando-tareas-repetitivas/

2024-04-21 17:39 UTC, Scot3004 commented
Numeral 1 resuelto, ya los eventos estan en cada hijo, si queremos mostrar el listado de los anexos, creo que habria que cambiar el script para que los anexos los deje en el campo attachment

Deje una lista de los pasos que me toco hacer ya que no fue poco y me toco echarle cabeza, si toca actualizar por que falten anexos, toca hacer toda esa vuelta de nuevo

2024-04-21 17:42 UTC, Scot3004 commented
Nota: el script create_events solo va a funcionar si se deja el eventos1 que se agrego aca, eso hay que eliminarlo, ya que la idea es que despues que se integre esto ya no usaremos el flowblock para la data, ademas de eliminar dicho archivo eventos1

2024-04-27 02:48 UTC, pyjavo approved these changes
TLDR; Estuvimos revisando en videollamada y agregamos cambios en algunas charlas del 2023 y 2024.
El resto

2024-04-27 02:49 UTC, merged