Aperez first pycon
PyBAQ/website pull request #515
Opened 2024-06-15 16:21 UTC by andoresuperesu

# Pull request

Blog Post Mi primera Pycon en español e Inglés con Imagen principal diferenciada en inglés y español

## Observaciones

Un recuento de mi experiencia de la Pycon un con todo el detalle que pude.

2024-06-15 23:18 UTC, pyjavo requested changes
Como siempre, un placer leer la escritura de Andrés. 
Hice unas sugerencias orientadas a ayudar a los lectores y a promocionar nuestros contenidos anteriores :P

2024-06-15 23:18 UTC, pyjavo commented on content/blog/mi-primera-pycon-como-voluntario/contents.lr
> +Después del primer ponente principal, tuve que correr y encontrar el Auditorio 101 donde debía asistir a los ponentes y la anfitriona. Estaba tan perdido, absolutamente silencioso pero gritando por d
"Lo siento Cristhian, había poco que pudiéramos hacer en ese momento para recuperar el tiempo perdido."
En esta frase me perdí como lector. ¿Por qué las disculpas? ¿Qué pasó? 
Es algo que deseas dejar así o agregarás contexto

Si quieres resaltar su participación considero que puedes agregar un enlace a su perfil de la PyCon Colombia
- https://2024.pycon.co/en/speakers/christian-urcuqui

2024-06-15 23:18 UTC, pyjavo commented on content/blog/mi-primera-pycon-como-voluntario/contents.lr
> +Después del primer ponente principal, tuve que correr y encontrar el Auditorio 101 donde debía asistir a los ponentes y la anfitriona. Estaba tan perdido, absolutamente silencioso pero gritando por d
Puedes compartirnos ¿Cuál era el propósito de crear un resumen para cada charla?

2024-06-15 23:18 UTC, pyjavo commented on content/blog/mi-primera-pycon-como-voluntario/contents.lr
> +Luego vino Edwin Enao y ya sabíamos que el video tenía sus problemas, pero también estaba claro que el equipo de transmisión estaba usando algún tipo de software similar a OBS[^vmix], habíamos aprend
¿OBS[^vmix] está bien escrito así con los corchetes? Solo por confirmar que no es un error de escritura

2024-06-15 23:18 UTC, pyjavo commented on content/blog/mi-primera-pycon-como-voluntario/contents.lr
> +Luego vino Edwin Enao y ya sabíamos que el video tenía sus problemas, pero también estaba claro que el equipo de transmisión estaba usando algún tipo de software similar a OBS[^vmix], habíamos aprend
"habíamos aprendido que vdo.ninja"...¿podrías compartirnos dónde lo aprendieron?

2024-06-15 23:18 UTC, pyjavo commented on content/blog/mi-primera-pycon-como-voluntario/contents.lr
> +Y el primer día terminó con Cristian Oña hablando sobre la automatización de pruebas de penetración con Python. Un tema que ya conocíamos de nuestro querido amigo [Sergio Molinares](https://pybaq.co/
Hay dos enlaces juntos y considero que se pierde la importancia de ambos. En términos de usabilidad, alguien con un dedo grande no podrá hacer click en el número 5 y siempre lo hará al perfil (se perdería el enfasis que haces sobre su charla). Dado que la charla ya incluye el enlace al perfil de Sergio M., por usabilidad y practicidad, considero solo dejar un unico enlace. Me refiero al enlace hacia [pentesting]

2024-06-15 23:18 UTC, pyjavo commented on content/blog/mi-primera-pycon-como-voluntario/contents.lr
> +En el 101, las cosas estaban claras, teníamos tareas y las completamos. Se suponía que debíamos ser una anfitriona y dos asistentes, pero lo habíamos manejado sin quejas. Gerardo Vilcamiza dio un cas
"Alejandro, si/cuando leas esto, recuerda..." 
¿Es correcto este uso de la diagonal en español? o será mejor usar "Alejandro, para cuándo leas esto, recuerda ..."

2024-06-15 23:18 UTC, pyjavo commented on content/blog/mi-primera-pycon-como-voluntario/contents.lr
> +Queremos ser acogedores con los principiantes en Python Barranquilla. También tuvimos una experiencia increíble durante el pasado esfuerzo con la Secretaría de Educación del Distrito de Barranquilla.
Sería bueno agregar el Enlace al artículo para promocionar nuestros antiguos artículos blog/experiencia-taller-sed/

2024-06-15 23:18 UTC, pyjavo commented on content/blog/mi-primera-pycon-como-voluntario/contents.lr
> +Realmente no sé por qué, pero la charla de Cris resonó tanto en mis pensamientos. Estaba impresionado, conmovido y motivado. Describió su viaje desde los estudios de música hasta la informática y Pyt
" Me encanta cómo describió a la Comunidad de Python de Colombia a los organizadores cuando le preguntaron cómo le había ido a lo largo del día."

¿Cómo describió a la comunidad de Python Colombia? ¿Es a propósito el misterio para con los lectores? Porque considero que sería bueno compartir que fue lo que dijo.

2024-06-15 23:18 UTC, pyjavo commented on content/blog/mi-primera-pycon-como-voluntario/contents.lr
> +Recuerdo estar cerca de Van y Matt durante la foto grupal del primer día, y escuché cuando Van mencionó que esperaba que su charla no se superpusiera demasiado con la de Matt. Y felizmente no lo hizo
"Van dio una clase magistral en realidad/razonabilidad alrededor de muchos escenarios de apocalíticos de IA --olvidense de terminator y Skynet-- ."

La leí un par de veces pero algo no me cuadra de esta oración. No se si es el uso de la preposición "de" antes de "apocalípticos".

Tal vez quisiste decir algo como "Van dio una clase magistral en realidad/razonabilidad alrededor de muchos escenarios, **desde** los más apocalíticos de IA --olvidense de terminator y Skynet-- **hasta** los más amigables."

Me cuentas qué opinas de esta sugerencia.

2024-06-19 02:46 UTC, andoresuperesu commented on content/blog/mi-primera-pycon-como-voluntario/contents.lr
> +Después del primer ponente principal, tuve que correr y encontrar el Auditorio 101 donde debía asistir a los ponentes y la anfitriona. Estaba tan perdido, absolutamente silencioso pero gritando por d
Para ser sincero ni yo lo sé, solo completé la tarea, jeje

2024-06-19 02:48 UTC, andoresuperesu commented on content/blog/mi-primera-pycon-como-voluntario/contents.lr
> +Luego vino Edwin Enao y ya sabíamos que el video tenía sus problemas, pero también estaba claro que el equipo de transmisión estaba usando algún tipo de software similar a OBS[^vmix], habíamos aprend
Es una error en el footnote que causa que no transformara la referencia en numeración, corregido.

2024-06-19 03:02 UTC, andoresuperesu commented
Dejé solo una imagen del articulo (en inglés) porque hay un bug con el manejo de links de imagenes en alternatives (varios idiomas) que solo está merged en la versión 3.4 de lektor, actualmente estamos en la 3.10.

Referencia:
https://github.com/lektor/lektor/issues/313
https://github.com/lektor/lektor/pull/992

2024-06-20 20:25 UTC, pyjavo approved these changes
¡¡Que gran trabajo!! Gracias por compartirnos tu experiencia

2024-06-20 20:25 UTC, merged