Jhoanrodriguez/add pylint GitHub actions
PyBAQ/website pull request #567
Opened 2024-10-26 16:48 UTC by JhoanRodriguez

# Pull request

Closes #397

## Observaciones

Garantizamos que en un nuevo cambio a los scripts python no estemos cometiendo potenciales faltas a los lineamientos de buenas practicas en python.

2024-10-26 17:46 UTC, Scot3004 commented
El job fallo
![image](https://github.com/user-attachments/assets/75a25f5c-510c-4ab9-8918-990c4d4e8cd6)

```
Run pylint --recursive=y tests scripts
  pylint --recursive=y tests scripts
  shell: /usr/bin/bash -e {0}
  env:
    DEPLOY: false
    OUTPUT: _html
    TZ: America/Bogota
    pythonLocation: /opt/hostedtoolcache/Python/3.10.15/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.10.15/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.15/x64
    Python[2](https://github.com/PyBAQ/website/actions/runs/11533428876/job/32107039814#step:6:2)_ROOT_DIR: /opt/hostedtoolcache/Python/[3](https://github.com/PyBAQ/website/actions/runs/11533428876/job/32107039814#step:6:3).10.15/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.15/x6[4](https://github.com/PyBAQ/website/actions/runs/11533428876/job/32107039814#step:6:4)
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.1[5](https://github.com/PyBAQ/website/actions/runs/11533428876/job/32107039814#step:6:5)/x64/lib
************* Module scripts.create_events
scripts/create_events.py:1:0: C0114: Missing module docstring (missing-module-docstring)
scripts/create_events.py:11:0: C011[6](https://github.com/PyBAQ/website/actions/runs/11533428876/job/32107039814#step:6:6): Missing function or method docstring (missing-function-docstring)
scripts/create_events.py:13:8: W0621: Redefining name 'events' from outer scope (line 51) (redefined-outer-name)
scripts/create_events.py:16:0: C0116: Missing function or method docstring (missing-function-docstring)
scripts/create_events.py:33:0: C0116: Missing function or method docstring (missing-function-docstring)
scripts/create_events.py:43:13: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
scripts/create_events.py:46:0: C0116: Missing function or method docstring (missing-function-docstring)
scripts/create_events.py:46:16: W0621: Redefining name 'events' from outer scope (line 51) (redefined-outer-name)

-----------------------------------
Your code has been rated at 9.1[7](https://github.com/PyBAQ/website/actions/runs/11533428876/job/32107039814#step:6:7)/10
```

2024-10-26 17:47 UTC, Scot3004 requested changes
Dado que el job fallo, creo que tocaria echarle una segunda revisada a los scripts debido a que el fallo estuvo en el create events

2024-10-29 14:26 UTC, Scot3004 approved these changes

2024-10-29 17:00 UTC, merged

2024-10-29 17:21 UTC, pyjavo commented
Muchas gracias por el aporte @JhoanRodriguez