Add pipreqs blog
PyBAQ/website pull request #568
Opened 2024-10-26 17:07 UTC by Kenneth3750

# Pull request

Closes #([numero de issue](https://github.com/PyBAQ/website/issues/566))

## Observaciones

Agregue una seccion al blog de python hablando sobre pipreqs y como favorece a la creacion de requirements.txt mas limpios :)

2024-10-26 17:58 UTC, Scot3004 commented
@pyjavo Tengo una duda respecto al blog post, se deja anonimo, o mejor crearle a kenneth un perfil como contribuidor?

2024-10-26 18:05 UTC, Scot3004 requested changes
El post se ve bien, pero se esta cambiando contenidos del content/Blog, que afecta negativamente el seo

2024-10-26 18:05 UTC, Scot3004 commented on content/blog/contents.lr
> -seo_description: Blog de la comunidad python Barranquilla, listado de entradas
Por favor no eliminar esto

2024-10-26 18:14 UTC, Scot3004 commented on content/blog/contents.lr
> -title: Blog
Por favor no eliminar el titulo

2024-10-29 17:31 UTC, pyjavo commented
Si, se puede dejar anónimo hasta que tenga suficientes puntos @Scot3004 

Quedamos a la espera de los cambios solicitados @Kenneth3750

2024-10-31 15:23 UTC, pyjavo commented
@Scot3004 volvi a colocar los textos que se habían borrado de `/content/blog/contents.lr`
¿Ahora si está ok para merge?

2024-10-31 15:24 UTC, pyjavo commented on content/blog/contents.lr
> -title: Blog
Hecho

2024-10-31 16:12 UTC, Scot3004 commented
Si, luz verde

2024-10-31 16:14 UTC, merged