Cambio de logo a version moderna
PyBAQ/website pull request #569
Opened 2024-10-26 17:11 UTC by jesubohr

# Pull request
Soluciona issue #543

## Observaciones

![image](https://github.com/user-attachments/assets/1d281ffd-6fdf-4abb-a66c-71f4bc6d4f3c)

2024-10-29 17:42 UTC, pyjavo commented
¡Muchas gracias! @jesubohr 
Por nuestra parte nos gustó bastante. Voy a verificar unos asuntos sobre la marca y si todo esta bien, acepto el PR

2024-10-29 17:45 UTC, pyjavo requested changes
Hay otras instancias donde estaría pendiente cambiar el logo.

1. En la sección de proyectos https://deploy-preview-569--vigilant-neumann-d109b9.netlify.app/proyectos/pagina-web/
2. En la pestaña (el favicon).

2024-10-30 15:42 UTC, pyjavo commented
@jesubohr ya la Python software Foundation nos aprobó el logo que hiciste. Tienes luz verde para continuar.

Por cierto, ¿cómo se llama la tipografía que usaste en el archivo .svg?

2024-10-30 15:55 UTC, jesubohr commented
> Hay otras instancias donde estaría pendiente cambiar el logo.
> 
> 1. En la sección de proyectos https://deploy-preview-569--vigilant-neumann-d109b9.netlify.app/proyectos/pagina-web/
> 2. En la pestaña (el favicon).

Listo, haré el cambio, gracias por la información 👌🏼

2024-10-31 06:03 UTC, jesubohr commented
> @jesubohr ya la Python software Foundation nos aprobó el logo que hiciste. Tienes luz verde para continuar.
> 
> Por cierto, ¿cómo se llama la tipografía que usaste en el archivo .svg?

Realmente no conozco el nombre debido a que lo generé usando uno generador de logos con IA, y no mencionaban el nombre de la fuente. Sin embargo, si es un problema, puedo buscar una fuente similar y que sea de uso libre.

2024-10-31 06:04 UTC, jesubohr reviewed
Update the logos and some styles

2024-10-31 15:16 UTC, pyjavo requested changes
¡Gracias!

Solo quedamos pendientes con el nombre de la fuente, porque si la necesitamos :sweat_smile:

2024-10-31 19:48 UTC, Scot3004 commented
<img width="1180" alt="image" src="https://github.com/user-attachments/assets/54b71526-b20a-4ce0-a19c-e311124b7689">

<img width="1148" alt="image" src="https://github.com/user-attachments/assets/3ea73774-c482-4d33-adb4-29c26e249c04">

2024-10-31 20:33 UTC, pyjavo commented
@Scot3004 ¡genio! Es esa.

¿Y para la palabra PYTHON BARRANQUILLA? ¿será la misma?

2024-10-31 20:52 UTC, pyjavo commented
Creo que puede ser una de estas opciones: 

- **Varta** https://fonts.google.com/specimen/Varta?preview.text=PYTHON%20BARRANQUILLA

- **Source sans 3** https://fonts.google.com/specimen/Source+Sans+3?preview.text=PYTHON%20BARRANQUILLA

- **Assistant** https://fonts.google.com/specimen/Assistant?preview.text=PYTHON%20BARRANQUILLA

2024-10-31 20:53 UTC, pyjavo approved these changes

2024-10-31 20:53 UTC, merged